### ISSUE TITLE
Getting bigger body response than actual

### ISSUE THREAD

**Issue by Netskyes** [codemanki/cloudscraper#143]
Hey, the response body is bigger than expected, if you go to from browser to http://osbot.org/mvc/get and see the response body, you'll see the size is different than when getting with cloudscraper. Thanks :)

**Comment by pro-src** [comment]
@Netskyes If I had to guess, you're not setting the `encoding` option. It defaults to utf8 which means the response is converted to a string which shouldn't be done for jar files. This is how `request/request` and `request/request-promise` work by default. Since cloudscraper uses `request-promise` you can expect the same behavior.

It should work properly if you account for the file type that you're requesting:
```js
var fs = require('fs');
var cloudscraper = require('cloudscraper');

cloudscraper.get({ encoding: null, uri: 'http://osbot.org/mvc/get' }).then(function (bodyAsBuffer) {
  fs.writeFileSync('./osbot.jar', bodyAsBuffer);
});
```

**Comment by Netskyes** [comment]
Thanks a lot @pro-src that was it, weirdly though previously I didn't set encoding and it worked fine, issue solved nonetheless :)
