### ISSUE TITLE
Where to test the reCaptcha ?

### ISSUE THREAD

**Issue by elpaxel** [codemanki/cloudscraper#202]
I want to test my captcha solving method but can't find any page with captcha triggered. Maybe there is some test pages or something ? Because I don't want to configure cf by myself. And I need "alive" page (not the one in fixtures folder) for domain/host mocking on local machine.

**Comment by pro-src** [comment]
I'll turn the CAPTCHA on for https://pro-src.com. Give me one sec to do it.

**Comment by elpaxel** [comment]
Thanks a lot :)

**Comment by pro-src** [comment]
You're welcome. Issue solved?

**Comment by elpaxel** [comment]
Yep.

**Comment by pro-src** [comment]
I'm looking for a consistent way to trigger CF's CAPTCHA on site's that don't have enabled in the same I've done for testing purposes. No luck yet..

**Comment by pro-src** [comment]
Theres a chance that if using cloudscraper though Tor that you'll get a CAPTCHA consistently. I haven't confirmed yet. The reason I suspect this is because this article mentions that the Tor team had to make a small change at the request of CF to avoid the CAPTCHAs and it only works for newer version of the Tor Browser. If that change was only made in Tor Browser, maybe we'll have some luck there.

Article: https://www.zdnet.com/article/cloudflare-ends-captcha-challenges-for-tor-users/

**Comment by pro-src** [comment]
Confirmed. You must override the headers entirely.

```sh
torsocks node -e 'var cf = require("."); cf.debug = true; cf.defaultParams.headers = {}; cf.get("http://gktorrent.net/torrents/series").then(console.log);'
```

**Comment by elpaxel** [comment]
Cool. Thanks for headers "trick".

**Comment by pro-src** [comment]
I better option that seems to be Cloudflare approved is https://captcha.website

**Comment by Revadike** [comment]
https://fuckmehard.fun/HIT

But it doesn't trigger onCaptcha for some reason...
