### ISSUE TITLE
Copy cookies to all requests in loop

### ISSUE THREAD

**Issue by lidorlevi156** [codemanki/cloudscraper#216]
Hello Guys,
I really worked hard and no result, all is failed.
I am trying to send one time request to Cloudflare UAM (5 Seconds), check if the request without errors and statusCode=200, copy the cookies to all requests in loop to avoid failures on bypassing cloudflare, without this it is very slow.
I really didn't understand the jar and requestModule, how to copy where to set and nothing.
Thanks for helping :)

**Comment by pro-src** [comment]
Hi @lidorlevi156,

You're right to be thinking about the `request` module if you're trying to get or set request related information. Their documentation should cover everything that you need to know: https://github.com/request/request

Just pretend that the `cloudscraper` library ***is*** the `request` library and everything should make sense.

The `request` library uses https://www.npmjs.com/package/tough-cookie to create the jar. The `tough-cookie` documentation should explain everything that you need to know about the jar object.

Documentation about loops:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

I can't help you further unless you ask a more specific question. Also please note that https://stackoverflow.com is better suited for general coding advice questions.

**Comment by lidorlevi156** [comment]
> Hi @lidorlevi156,
> 
> You're right to be thinking about the `request` module if you're trying to get or set request related information. Their documentation should cover everything that you need to know: https://github.com/request/request
> 
> Just pretend that the `cloudscraper` library _**is**_ the `request` library and everything should make sense.
> 
> The `request` library uses https://www.npmjs.com/package/tough-cookie to create the jar. The `tough-cookie` documentation should explain everything that you need to know about the jar object.
> 
> Documentation about loops:
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
> 
> I can't help you further unless you ask a more specific question. Also please note that https://stackoverflow.com is better suited for general coding advice questions.

Hi @pro-src,
I just want to ask if it is possible to send one request to site that have 5 seconds cloudflare and when the request is success, to copy the cookies and start loop of requests with the cookies of the first request, it will work or cloudflare will check for 5 seconds no matter the cookies because the ip changing (proxy loop).
Thank you :)

**Comment by pro-src** [comment]
If you can, you're better off using Cloudscraper for all of your requests. It won't slow you down since it skips a lot of checks when it can.

The answer to your question is ***yes*** but how will you know whenever another challenge is sent?
Yes, you could share the cookie and only solve one 5 sec challenge every 30 mins. The cookie will expire after 30 mins. However, it is also possible for Cloudflare to send challenges even with the cookie set. You could solve 1 challenge, get/set the correct cookie and still wind up having to solve another challenge with your very next request. ***It is a very common pattern for Cloudflare to ignore the cookie (at seemingly random intervals) and send you additional challenges.***

Cloudflare's BIC is smart and getting smarter. I seriously doubt that you're not going to have problems if you don't let Cloudscraper handle the requests for you.

I wish you best the luck with your endeavors.

**Comment by pro-src** [comment]
@lidorlevi156 Regarding the IP changing, Cloudflare will probably send you a CAPTCHA if you reuse the cookie in that case. If you so much as use a different UA with the cookie, Cloudflare will more than likely flag you. Using the same IP and making requests using Cloudscraper in a loop shouldn't be a problem at all. I hope I cleared everything up for you.

**Comment by lidorlevi156** [comment]
@pro-src Thank you, I understood everything.
