### ISSUE TITLE
challengeId (jschl_vc) extraction failed

### ISSUE THREAD

**Issue by ikozehh** [codemanki/cloudscraper#227]
Currently doing a post request to a website to add an item to cart

```
`      async function cart(token, cartProductID, bsID, secretfindel){
        const cartqs = querystring.decode("hash=61b936cfa4ee4280e5e22a6af0bf6031&secret=eyJ0aW1lc3RhbXAiOjE1NTkxMTYzMTgsImFjdGlvbiI6IlwvZW5cL2NhcnRcL3BsdXNcL2RjYmMwLTExMTA1MSJ9&product_id=164768&product_bs_id=111051&amount=1&ajax=true&redirectRooting=&addToCart=&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5Bmodule%5D=cart&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5BpartialName%5D=cartHeader&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5BreturnName%5D=headerCartDesktop&returnHtmlSnippets%5Bpartials%5D%5B0%5D%5Bparams%5D%5Btemplate%5D=Standard&returnHtmlSnippets%5Bpartials%5D%5B1%5D%5Bmodule%5D=cart&returnHtmlSnippets%5Bpartials%5D%5B1%5D%5BpartialName%5D=cartHeader&returnHtmlSnippets%5Bpartials%5D%5B1%5D%5BreturnName%5D=cartErrors&returnHtmlSnippets%5Bpartials%5D%5B1%5D%5Bparams%5D%5Btemplate%5D=errorMessage&returnHtmlSnippets%5Bpartials%5D%5B2%5D%5Bmodule%5D=cart&returnHtmlSnippets%5Bpartials%5D%5B2%5D%5BpartialName%5D=cartHeader&returnHtmlSnippets%5Bpartials%5D%5B2%5D%5BreturnName%5D=headerCartMobile&returnHtmlSnippets%5Bpartials%5D%5B2%5D%5Bparams%5D%5Btemplate%5D=mobileNavbar&returnHtmlSnippets%5Bpartials%5D%5B3%5D%5Bmodule%5D=product&returnHtmlSnippets%5Bpartials%5D%5B3%5D%5Bpath%5D=_productDetail&returnHtmlSnippets%5Bpartials%5D%5B3%5D%5BpartialName%5D=buybox&returnHtmlSnippets%5Bpartials%5D%5B3%5D%5BreturnName%5D=buybox&returnHtmlSnippets%5Bpartials%5D%5B3%5D%5Bparams%5D%5BbsId%5D=111051&returnHtmlSnippets%5Bpartials%5D%5B4%5D%5Bmodule%5D=cart&returnHtmlSnippets%5Bpartials%5D%5B4%5D%5BpartialName%5D=modalWasadded");
        cartqs.hash = token;
        cartqs.product_id = cartProductID;
        cartqs.product_bs_id = bsID,
        cartqs.secret = secretfindel;
        return cloudscraper.post({
          uri : "https://www.bstn.com/en/cart/add",
          headers : headers,
          formData : cartqs,
          proxy : proxy,
          resolveWithFullResponse:true
        }).then(body => {
          console.log(body);
        }).catch(e => {
          console.log("error " + e);
        })
      }`
```

This is following a get request to https://www.bstn.com/en/p/nike-wmns-air-force-1-07-lx-898889-101-111045
and retrieving the hash, secret, product variant and the product ID. I get the error 
challengeId (jschl_vc) extraction failed
I turned debug on for cloudscraper and can see I have a 503 response error but cannot see any other further information in debugging that may help me

Trying this post request which is an alternative one also gives me cloudflare 1020 error:

async function cart(token, cartProductID, bsID, secretfindel){
        ```
const cartqs = querystring.decode("hash=61b936cfa4ee4280e5e22a6af0bf6031&secret=eyJ0aW1lc3RhbXAiOjE1NTkxMTYzMTgsImFjdGlvbiI6IlwvZW5cL2NhcnRcL3BsdXNcL2RjYmMwLTExMTA1MSJ9&product_id=164768&product_bs_id=111051&amount=1");
        cartqs.hash = token;
        cartqs.product_id = cartProductID;
        cartqs.product_bs_id = bsID,
        cartqs.secret = secretfindel;
        return cloudscraper.post({
          uri : "https://www.bstn.com/en/cart/item",
          headers : headers,
          formData : cartqs,
          proxy : proxy,
          resolveWithFullResponse:true
        }).then(body => {
          console.log(body);
        }).catch(e => {
          console.log("error " + e);
        })
      }
```

**Comment by codemanki** [comment]
@ikozehh thanks for reporting this. Does this also happen with GET requests or only in this specific scenario?

**Comment by ikozehh** [comment]
Haven't had it happen with get requests, only this specific scenario I've found it but I cant do any further post requests to check unless this one is done, the GET works fine

**Comment by pro-src** [comment]
The URL is wrong. The service doesn't actually post to https://www.bstn.com/en/cart/item when I add an item to the cart. It changes the URL to match the product: https://www.bstn.com/en/cart/plus/dc44a-111048.

In any case, I'd think the other errors are due to a custom error page.
If you want help with this, you're going to have to do the work. Meaning, provide us with a minimal working code snippet that reproduces the problem.

**Comment by pro-src** [comment]
And example code snippet from your other issue: https://github.com/codemanki/cloudscraper/issues/222#issuecomment-496297306

I'd expect something similar that can reproduce a problem with cloudscraper.

**Comment by pro-src** [comment]
I reproduced the error (edited to remove embedded base64, etc.):
```html
<!DOCTYPE html>
<html lang="de-DE"><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width">
<meta charset="UTF-8">
<title>BSTN Store / Sorry, We're Open</title>
</head>
<body id="blocked-load">
<div class="message">
</p>
<div>
<p>Der Zugriff auf den Shop wurde automatisch eingeschränkt, da die maximale Anzahl von aktiven Shop Usern bereits erreicht wurde. Sobald die aktiven Shop User ihren Checkout abgeschlossen haben, lässt der Server automatisch neue Zugriffe auf den Onlineshop zu.</p>
<p><strong>Danke für dein Verständnis - BSTN salutes you!</strong></p>
<p>&nbsp;</p>
<p class="text-en" style="margin-top:15px;">Unfortunately our online shop has reached the maximum number of active shop users. As soon as active shop users complete their checkout, the server will grant access to new shop users.</p>
<p class="text-en"><strong>Thanks for your understanding - BSTN salutes you!</strong></p>
</div>
</div>
</body>
</html>
```

IMHO, The server erroneously uses the same HTTP server error status code as Cloudflare. I don't really think this should be fixed because if Cloudflare changes their markup we could return bogus data to clients without them knowing.

In conclusion, the errors aren't caused by Cloudscraper but rather by bad requests. Cloudscraper is being confused by the server error and mistakenly reporting this as an internal error.

**Comment by pro-src** [comment]
@ikozehh Explanation:

If the HTTP response header `Server: cloudflare` is present and the content type is `text/html`, the following checks will be performed along with checks for reCAPTCHA:
https://github.com/codemanki/cloudscraper/blob/c3c4339c9c5c765ee03d702b1df15227a9650c80/index.js#L207

https://github.com/codemanki/cloudscraper/blob/c3c4339c9c5c765ee03d702b1df15227a9650c80/index.js#L220-L223

* If the IUAM challenge response is sent with a different HTTP status code i.e. `429 Too Many Request`, Cloudscraper will still detect it because the response body includes `a = document.getElementById(\'jschl-answer\`.

* If the IUAM challenge response body changes to no longer include `a = document.getElementById(\'jschl-answer\`, we'll still detect it because of the status code.

If we only ever detect challenges based on status code and content, we run the risk of failing to detect challenges altogether. Failing to detect challenges, would result in unintended behavior and/or cause other errors.

Summing it up:
> If a Cloudflare protected server reports errors using the 503 HTTP status code, Cloudscraper will misinterpret the response as an IUAM challenge response and is likely to report parser errors.

Thanks again for opening this issue.
