### ISSUE TITLE
noob wants to bypass ReCaptcha

### ISSUE THREAD

**Issue by Nameless9** [codemanki/cloudscraper#254]
Hello,

I'm using an API from a site that's facing some issues and they implemented ReCaptcha. However, to provide my own bot services, I need to bypass the Recaptcha lol.

I've looked at your example pages: https://github.com/codemanki/cloudscraper/blob/HEAD/docs/examples/solve-recaptcha.js
and
https://github.com/codemanki/cloudscraper/blob/HEAD/docs/examples/solve-recaptcha-v2.js

I have trouble with using this example. let's say I'm using the non-promise version (non- v2 page), I see that the key code to solve ReCaptcha's are the `solveReCAPTCHA` method that isn't provided to us. I am able to see URL and siteKey from the header. I think I've may be seen an issue that I need to provide my own methods for this. Can you help me understand how to provide this method? 

thanks

**Comment by pro-src** [comment]
Hi @Nameless9,

It should be a straight-forward process once you understand a couple of concepts.

* Cloudscraper doesn't solve the CAPTCHA at all, it does provide you an API and the information you need to solve the CAPTCHA yourself via third party services suchas anti-captcha.com.
* Services such as anti-captcha.com should document how to use their services to solve CAPTCHA.

So with that in mind, if you head over to https://anti-captcha.com/mainpage, you'll see the `Documentation` link in the navigation header (very top center of the page). It's impossible to miss.

The docs link is https://anti-captcha.com/apidoc/image. The page shows an examples and links to examples in multiple languages. As you'd expect there is one for Node.js: https://github.com/AdminAnticaptcha/anticaptcha-nodejs

So finding this information is either 123 or you're better off using a different service...

The examples there should suffice but if you're still struggling, maybe open an issue there: https://github.com/AdminAnticaptcha/anticaptcha-nodejs/issues (or stackoverflow.com)?

Or since you'd be paying for the service, contact support.

Cheers
