### ISSUE TITLE
How to cancel a request?

### ISSUE THREAD

**Issue by waltaki** [codemanki/cloudscraper#262]
For example, I need to download a file. 
In the beginning I will get the headers, check them, for example for the file extension, and if this extension does not suit me, I go to stop receiving the file, do abort. 

How do I imagine it:

```
let get = this.scraper.get(url)

get.onResponse(({ caseless }) => {
  let fileName = caseless.get("content-disposition").match(/filename\*?=['"]?(?:UTF-\d['"]*)?([^;\r\n"']*)['"]?;?/i)[1]
	if(fileName != 'jar') {
		get.abort()
	}
});

get.onResponseEnd(({ caseless, body }) => {
	let fileName = caseless.get("content-disposition").match(/filename\*?=['"]?(?:UTF-\d['"]*)?([^;\r\n"']*)['"]?;?/i)[1]
	if(fileName != 'jar') {
		get.abort()
	} else {
		this.storage.saveFile(body)
	}
});
```
Also, implementation would be very good as `Interceptor`, that is, to prevent packets from being received until I `continue`.

How to implement this?

**Comment by pro-src** [comment]
Hi @waltaki,

Yes, this a bug.

It's not currently possible to abort requests that were redirected due to challenge solving. The number of challenges to solve can be configured by using the `challengesToSolve` option (defaults to 3).  *The request can be aborted during normal redirects or if challenges aren't encountered.*

```js
const cloudscraper = require('cloudscraper');
const request = cloudscraper.get('https://example.com')

request.abort()
```

Workaround:
* Ensure that you have the `cf_clearance` cookie in advance e.g. prefetch a protected url.
* Perform an actual HEAD request
* Conditionally proceed to perform a GET request

PR's welcome.
