### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [codemanki/cloudscraper#49]
@codemanki : 
Hi, I wanted to know if it works on react-native.
I tried to install it but it does not seem to work, from problems with addictions.
So I wanted to know is it possible to make it work on react-native?

**Comment by Angelk90** [comment]
Hi @codemanki, would it be possible to have an answer?

**Comment by codemanki** [comment]
Hey @Angelk90 if you could share more details about errors you are getting, and maybe sharing the code i would be able to help you a bit

**Comment by pro-src** [comment]
@Angelk90 That's a very interesting question.

Looks you'd want to use https://code.janeasystems.com/nodejs-mobile/
https://github.com/janeasystems/nodejs-mobile/releases
```json
{ "http_parser" : "2.8.0"
  ,"mobile" : "0.2.1"
  ,"node" : "10.13.0"
  ,"v8" : "6.8.275.32-node.36"
  ,"chakracore" : "1.11.1.0"
  ,"uv" : "1.23.2"
  ,"zlib" : "1.2.11"
  ,"ares" : "1.14.0"
  ,"modules" : "64"
  ,"nghttp2" : "1.34.0"
  ,"napi" : "3"
  ,"openssl" : "1.1.0i"
}
```

I'm not aware of any incompatibility with either of the above engines (v8 or Chakra) for Node.js. I imagine that everything would work fine when configured correctly.
The ChakraCore version is recent enough. https://github.com/microsoft/ChakraCore/releases
The Node.js version is recent enough. The only thing that stands out is the openssl version. It's a tad outdated but that shouldn't be a problem.

So in addition to @codemanki's request, what are you actually using to run Cloudscraper?

**Comment by Angelk90** [comment]
@codemanki : 
Problem:
```
Device: (1053:881) Unable to resolve module 'module://net.js'
  Evaluating module://net.js
  Evaluating module://cloudscraper.js
  Evaluating module://App.js.js
  Loading module://App.js
```

Link: https://snack.expo.io/r1aK3PenE

I was hoping to be able to use it normally without being js as well, but it seems that the dependencies don't work properly and they conflict with react-native.

At first I used react-native-cloudscraper, it worked fine but now it seems that it doesn't work properly anymore, besides its developer seems to have abandoned the project in question.

@pro-src : What I was asking if it was possible to develop a module that could work for react-native, since there is one for nodejs, even based on react-native-cloudscraper.

**Comment by pro-src** [comment]
@Angelk90 I'm not sure that you've answered the question of what you're actually using to run cloudscraper in term's of the JS engine which must be used to execute JS.

The error isn't related to cloudscraper and I don't think it's related to Node.js either. I'm guessing but it looks the result of a failed build due to some module resolution logic that is outside of Node.js.

> @pro-src : What I was asking if it was possible to develop a module that could work for react-native, since there is one for nodejs, even based on react-native-cloudscraper.

It should work just fine without any modifications when using the plugin that I mentioned or a similar react-native plugin/component. I really don't think this is the fault of your project's dependencies but rather some misunderstanding of how the components of a react-native project work together and/or some misconfiguration.

Sorry but since it's out of the scope of this project, I don't really see how we can be of much more help. I would ask this question on https://stackoverflow.com if you're stomped.

**Comment by pro-src** [comment]
@Angelk90 Sorry, if I failed to realize the question in some way. I'll add that this is a Node.js project and it needs Node.js to function properly. Good luck man :smile:
