### ISSUE TITLE
Prepare v3.0.0 release

### ISSUE THREAD

**Issue by codemanki** [codemanki/cloudscraper#99]
- [x] Rewrite README to reflect new changes
- [x] Add upgrade guide for 2.0 -> 3.0

**Comment by Revadike** [comment]
Include a changelog maybe? The commit messages aren't that clear.

**Comment by pro-src** [comment]
@Revadike There is a CHANGELOG.md on the master branch. It would be updated...

**Comment by pro-src** [comment]
@Revadike also the changes can simply be summarized as it is now a drop-in replacement for `request-promise`.

**Comment by pro-src** [comment]
@Revadike, here is a summary of the changes until we have a chance to update the changelog while we prepare this release.

* The error objects are now custom instances of Error and have additional properties.
  * `options` - The request options
  * `cause` - An alias for `error`
  * `response` - The request response
* The signature of get/post methods changed to match request-promise
* The `cloudscraper.request` method was removed, can just call `cloudscraper(options)`.
* There is now a `cloudflareTimeout` option
* Bug fixes, some are security related
* It is now a drop-in replacement for request-promise
* Nearly 100% code coverage
* Various other improvements

**Comment by codemanki** [comment]
@pro-src @Revadike i will include all these in the changelog

**Comment by pro-src** [comment]
@codemanki, I meant to say, why wouldn't you update the changelog _that you added to the master branch_. It goes without saying. I think @Revadike just didn't see it or doesn't realize that this hasn't been released yet.

**Comment by pro-src** [comment]
I think the greatest feature of v3.0.0 is being a drop-in replacement for request-promise but theres still a couple of issues standing in the way of that.

#105, #115, and #117

**Comment by pro-src** [comment]
I should have these cleared up as soon as I know the answer to my question in #116

**Comment by Revadike** [comment]
I actually have a small question. Can you use this library as a complete replacement for `node-request`? Earlier you couldn't use `request.defaults` and set `jar` to `true`, but you seem to have a solution for that now. I may be wrong about this, but I suspected it would always wait some seconds, even if the site didn't support cloudflare, therefore slowing down web requests for no reason. What I'm trying to ask is, would this library perform as good as the basic `node-request` library?

**Comment by pro-src** [comment]
@Revadike 
> I actually have a small question. Can you use this library as a complete replacement for node-request

Yes but there a few open issues related to that.

> Earlier you couldn't use request.defaults and set jar to true, but you seem to have a solution for that now. I may be wrong about this, but I suspected it would always wait some seconds, even if the site didn't support cloudflare, therefore slowing down web requests for no reason.

Actually, that was never a problem. It will only wait if a challenge is detected but see #116 (I have to rebase that PR and its a WIP).

> What I'm trying to ask is, would this library perform as good as the basic node-request library?

Yes but there are optimizations that the library user can make to request and/or cloudscraper, depending on their use case. The setTimeout delay is eventually going to be parsed out and I have another idea on how to make the delay more exact. But even with those optimizations if you were sent 3 challenges, it'd still take 15 seconds. Meaning, worst case scenario where the request does not error, it'd only possibly be 3 seconds faster.

**Comment by pro-src** [comment]
@Revadike, I thought that I should mention that there is not any stream support. So you can't pipe things around or listen to data events. I had initially added this but dropped it because it kills maintainability. At one point, I almost had `request`'s entire unit test suite passing for cloudscraper but it was a mess. If you must use `request` and not `request-promise`, you can use the `requester` option to pass your own library to cloudscraper. If using `request` instead of `request-promise`, the callback is mandatory. The reason why it's so hard to mock `request` is because of it's code architecture. Somebody spent 3 months rewriting the entire code base to solve that problem and the rewrite boasts very nice modularity. It would make this a walk in the park but it was never fully adopted (I don't know why).

You can read about the issue here: https://github.com/request/request/issues/1982 
The core code: https://github.com/request/core
The version that depends on core but is backwards compatible: https://github.com/request/legacy

It is published on npm but since it's been years and it still hasn't been fully adopted, I don't see it as being a good replacement for us to use, if solely for the purpose of adding stream support.
